version: 2

models:
  - name: clean_stock_data
    description: "Cleaned stock data with formatted fields and filtered anomalies."
    columns:
      - name: symbol
        description: "Stock ticker symbol."
        tests:
          - not_null
      - name: date
        description: "Trading date."
        tests:
          - not_null
      - name: open
        description: "Opening price of the stock."
      - name: close
        description: "Closing price of the stock."
        tests:
          - not_null
      - name: high
        description: "Highest price during the trading session."
      - name: low
        description: "Lowest price during the trading session."
      - name: volume
        description: "Total trading volume."
        tests:
          - not_null
      - name: updated_at  # Newly added field for tracking data updates
        description: "Timestamp indicating last modification of the record."
        tests:
          - not_null  # Ensures every record has an update timestamp

  - name: transform_stock_metrics
    description: "Processed stock data with calculated indicators: price change %, moving averages, volume averages, and RSI(14)."
    columns:
      - name: symbol
        description: "Stock ticker symbol."
        tests:
          - not_null

      - name: date
        description: "Trading date."
        tests:
          - not_null

      - name: close
        description: "Closing price used for further calculations."
        tests:
          - not_null

      - name: price_change_pct
        description: "Daily price change percentage compared to the previous day."

      - name: high_low_diff
        description: "Difference between the highest and lowest price of the day."

      - name: moving_avg_20d
        description: "20-day moving average of the closing price."

      - name: moving_avg_50d
        description: "50-day moving average of the closing price."

      - name: moving_avg_200d
        description: "200-day moving average of the closing price."

      - name: volume_avg_7d
        description: "7-day average of trading volume."

      - name: rsi_14
        description: "14-day Relative Strength Index (RSI) based on average gain and loss."
        tests:
          - not_null

      - name: updated_at
        description: "Timestamp of the last update."
        tests:
          - not_null